modules=(
    modkey
    font
    i3-gaps
    i3-colors
    keybindings
    keybindings_window
    keybindings_layout
    keybindings_workpaces
    media-hotkeys
    workspaces
    code_sudo_fix
    autostart
    background_image
    polybar
    scratchpad
    window_rules
    floating_windows
    mouse_focus
    phone_connect_wireless
    system_power_mode
)
